# THIS type(variable name) IS USED TO FIND OUT THE TYPE OF DATA WE ENTERED IN THE VARIABLE
name = "Muhammad Faizan"
floating = 2548.052
print(type(floating))
print(type(name))

name1 = "Muhammad Faizan"
floating1 = 2548.052
print(str(floating1) + name1)

""" HERE WE ADD TWO VALUES OF DIFFERENT DATA TYPE WITH THE HELP OF TYPECASTING. IF YOU ARE ADDING AN INTEGER VALUE IN A STRING VALUE SO
SIMPLY WE HAVE TO CONVERT THAT INTEGER VALUE INTO THE STRING VALUE LIKE THIS [str(variable name which is in integer) + string variable name]"""

print("WHAT IS YOUR NAME: ")
name = input()        # SO HERE IF WE WANT TO TAKE INPUT FROM THE USER SO WE CAN TAKE IT LIKE THIS WITH THE HELP OF INPUT KEYWORD
print("MY NAME IS: ", name)

""" SO RIGHT NOW THIS INPUT KEYWORD IS ONLY TAKING THE STRING DATA AS AN INPUT SO IF WE WANT TO TAKE THE INPUT OF ANY OTHER DATA TYPE
LIKE INTEGER OR FLOAT SO SIMPLY WE HAVE TO GIVE THAT INPUT KEYWORD A DATA TYPE """

print("WHAT IS YOUR AGE: ")
age = int(input())     # WITH THE HELP OF DATA TYPE OF INTEGER GIVEN TO INPUT KEYWORD WE CAN GIVE IT AN INPUT OF INTEGER ONLY.
print("MY AGE IS: ", age)

print("WHAT IS YOUR PERCENTAGE IN INTERMEDIATE: ")
percent = float(input())       # WITH THE HELP OF DATA TYPE OF FLOAT GIVEN TO INPUT KEYWORD WE CAN GIVE IT AN INPUT OF DECIMAL AND INTEGER ONLY.
print("MY PERCENTAGE IN INTERMEDIATE IS: ", percent)