print("SINGLE LINE COMMENT IS DONE WITH THE HELP OF HASH(#)")
print("MULTIPLE LINE COMMENT IS DONE WITH THE HELP OF DOUBLE INVERTED COMMAS")

# SINGLE LINE COMMENT = HASH(#)
# MULTIPLE LINE COMMENT = DOUBLE INVERTED COMMAS THREE TIMES(""" """)

print("MUHAMMAD FAIZAN", end= " SON OF ") 
print("MUHAMMAD ARIF")

print("\n\twhat\thappened\tto\tyou")

# \n = PRINT ANYTHING IN NEW LINE
# \t = PRINT ANYTHING WITH SOME SPACE
# \\ = PRINT BACKSLASH 

print("THE SYMBOL OF BACKSLASH IS: \\")